# This file was generated by GoReleaser. DO NOT EDIT.
cask "erdo" do
  name "erdo"
  desc "CLI tool for Erdo AI platform"
  homepage "https://github.com/erdoai/homebrew-tap"
  version "0.1.28"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "erdo"

  on_macos do
    on_intel do
      url "https://github.com/erdoai/homebrew-tap/releases/download/v#{version}/erdo-cli_Darwin_x86_64.zip"
      sha256 "b8978f42a0460e470e53cb592e8d114c6c0053cedbd1fd89f3fdf5459acbb594"
    end
    on_arm do
      url "https://github.com/erdoai/homebrew-tap/releases/download/v#{version}/erdo-cli_Darwin_arm64.zip"
      sha256 "5171c25ba80bfe7ffd12637205561a1d43ff11451045c29cb149d94d2430a1a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/erdoai/homebrew-tap/releases/download/v#{version}/erdo-cli_Linux_x86_64.zip"
      sha256 "2c6298b46b1773fe0a8496a3f00e2446623933e0d2ab44f6894046b6353ee011"
    end
    on_arm do
      url "https://github.com/erdoai/homebrew-tap/releases/download/v#{version}/erdo-cli_Linux_arm64.zip"
      sha256 "79d4dbedaae2b47eb6b646737632a297e9d6cee2a85687ea665d3e05d1a0b0e6"
    end
  end

  # No zap stanza required
end
